services:
  mysql:
    image: mysql:8.0
    container_name: ford-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ford2024!}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ford_db}
      MYSQL_USER: ${MYSQL_USER:-ford_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ford_pass}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ford-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ford-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-ford_db}
      DB_USERNAME: ${MYSQL_USER:-ford_user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-ford_pass}
      JWT_SECRET: ${JWT_SECRET:-ford-secret-key-2024-muito-segura-para-jwt-token}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ford-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ford-frontend
    environment:
      API_URL: http://localhost:${BACKEND_PORT:-8080}/api
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ford-network

volumes:
  mysql_data:

networks:
  ford-network:
    driver: bridge
